export const LOGIN_ROUTE = '/Login'
export const SHOW_ICON = "SHOW_ICON"
export const HIDE_ICON = "HIDE_ICON"

export const API_POST_LOGIN = "https://sunmadebackend.herokuapp.com/api1/v1/login/"
export const API_GET_STAFF_COURIER = 'https://sunmadebackend.herokuapp.com/api1/v1/registerstaff/?is_active=true&usertype=runner'
export const API_GET_STAFF_FLORIST = 'https://sunmadebackend.herokuapp.com/api1/v1/registerstaff/?is_active=true&usertype=florist'
export const API_GET_STAFF_ADMIN = 'https://sunmadebackend.herokuapp.com/api1/v1/registerstaff/?is_active=true&usertype=admin'
export const API_GET_STAFF_COURIER_UNACTIVE = 'https://sunmadebackend.herokuapp.com/api1/v1/registerstaff/?is_active=false&usertype=runner'
export const API_GET_STAFF_FLORIST_UNACTIVE = 'https://sunmadebackend.herokuapp.com/api1/v1/registerstaff/?is_active=false&usertype=florist'
export const API_GET_STAFF_ADMIN_UNACTIVE = 'https://sunmadebackend.herokuapp.com/api1/v1/registerstaff/?is_active=false&usertype=admin'

export const API_GET_GOODS = 'https://sunmadebackend.herokuapp.com/api/products/'
export const API_POST_REGISTER_STAFF = 'https://sunmadebackend.herokuapp.com/api1/v1/registerstaff/'
export const API_GET_PRODUCT = 'https://sunmadebackend.herokuapp.com/products/89/'
export const API_GET_CATEGORY = "https://sunmadebackend.herokuapp.com/api/categories/"
export const API_GET_BRANCH = "https://sunmadebackend.herokuapp.com/api1/v1/branch/"
export const API_GET_ORDER = "https://sunmadebackend.herokuapp.com/api/order/?status=new"
export const API_GET_ORDER_PROCESSED = "https://sunmadebackend.herokuapp.com/api/order/?status=processed"
export const API_GET_ORDER_COMPLETED = "https://sunmadebackend.herokuapp.com/api/order/?status=completed"
export const API_GET_SALARY_STAFF = 'https://sunmadebackend.herokuapp.com/delivery_by/40/'

export const SIGN_IN = "SIGN_IN"
export const GET_PRODUCT = "GET_PRODUCT"
export const REGISTER_STAFF = "REGISTER_STAFF"
export const REGISTER_FAILURE = "REGISTER_FAILURE"
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE'
export const GET_STAFF = "GET_STAFF"
export const GET_GOODS = 'GET_GOODS'
export const SIGNIN_FORM_STARTED = "SIGNIN_FORM_STARTED"
export const SIGNIN_FORM_SUCCESS = "SIGNIN_FORM_SUCCESS"
export const USER_TYPE = "USER_TYPE"
export const CLEAR_ERR = "CLEAR_ERR"
export const JWT_TOKEN = "JWT_TOKEN"
export const CLEAR_RES = "CLEAR_RES"
export const PAGINATION_GOODS = "PAGINATION_GOODS"
export const PAGINATION_STAFF = "PAGINATION_STAFF"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const GET_CATEGORY = "GET_CATEGORY"
export const GET_GOODS_BY_CATEGORY = "GET_GOODS_BY_CATEGORY"
export const GET_ONE_STAFF = "GET_ONE_STAFF"
export const GET_BRANCH = "GET_BRANCH"
export const IS_ACTIVE = "IS_ACTIVE"
export const GET_ORDER = "GET_ORDER"
export const GET_SALARY = "GET_SALARY"
export const PAGINATION_ORDER = "PAGINATION_ORDER"
export const DELETE_ORDER ="DELETE_ORDER"
export const GET_ORDER_BY_ID = "GET_ORDER_BY_ID"
export const CHANGE_GOODS_INPUT = "CHANGE_GOODS_INPUT"
export const DELETE_BRANCH = "DELETE_BRANCH"
export const CHANGE_INPUT_ADRESS = "CHANGE_INPUT_ADRESS"
export const GET_BRANCH_BY_ID = "GET_BRANCH_BY_ID"